// <auto-generated />
using System;
using API_Web_Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Web_Core.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20220727030813_firstMigrate")]
    partial class firstMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_Web_Core.Models.PivotUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PivotId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PivotUserRole");
                });

            modelBuilder.Entity("API_Web_Core.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleDescription")
                        .HasColumnType("text")
                        .HasColumnName("role_description");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("role_key");

                    b.Property<int?>("parentID")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("RoleId");

                    b.HasIndex("parentID");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("API_Web_Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_password");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("API_Web_Core.Models.PivotUserRole", b =>
                {
                    b.HasOne("API_Web_Core.Models.Role", "Role")
                        .WithMany("PivotUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Web_Core.Models.User", "User")
                        .WithMany("PivotUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_Web_Core.Models.Role", b =>
                {
                    b.HasOne("API_Web_Core.Models.Role", "Parent")
                        .WithMany("childRoles")
                        .HasForeignKey("parentID")
                        .HasConstraintName("FK__pivot_parent__role___4A75D761");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("API_Web_Core.Models.Role", b =>
                {
                    b.Navigation("childRoles");

                    b.Navigation("PivotUserRoles");
                });

            modelBuilder.Entity("API_Web_Core.Models.User", b =>
                {
                    b.Navigation("PivotUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
